// the-net-pizza-react/the-net-pizza/src/components/Menu.js
import React from "react";
import MenuItem from "./MenuItem";

export default function Menu({ piatti }) {
  return (
    <section className="menu">
      <div className="row">
        <div className="col-12">
          <h2 className="section-title">I Nostri Piatti</h2>
          <div className="separator"></div>
        </div>
      </div>
      <div className="row">
        <div className="col-12 pt-5 pb-2">
          <h3>Antipasti</h3>
        </div>
        {piatti
          .filter((x) => x.category === "antipasti")
          .map((piatto, index) => (
            <MenuItem key={index} piatto={piatto} />
          ))}
      </div>

      <div className="row ">
        <div className="col-12 pt-5 pb-2">
          <h3>Primi</h3>
        </div>
        {piatti
          .filter((x) => x.category === "primi")
          .map((piatto, index) => (
            <MenuItem key={index} piatto={piatto} />
          ))}
      </div>

      <div className="row ">
        <div className="col-12 pt-5 pb-2">
          <h3>Dolci</h3>
        </div>
        {piatti
          .filter((x) => x.category === "dolci")
          .map((piatto, index) => (
            <MenuItem key={index} piatto={piatto} />
          ))}
      </div>
    </section>
  );
}

// the-net-pizza-angular/src/app/menu/menu.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Piatto } from '../@models/menu';
import { MenuService } from '../@services/menu.service';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent implements OnInit {

  piattiAntipasti: Piatto[] = [];
  piattiPrimi: Piatto[] = [];
  piattiDolci: Piatto[] = [];

  constructor(private menuService: MenuService) {
  }

  ngOnInit(): void {
    const getMenuObservable = this.menuService.getMenu()
    
    getMenuObservable.subscribe({
      next: (piatti) => {
        this.piattiAntipasti = piatti.filter(x => x.category === 'antipasti');
        this.piattiPrimi = piatti.filter(x => x.category === 'primi');
        this.piattiDolci = piatti.filter(x => x.category === 'dolci');
      }
    });
  }
}

<!-- MENU SECTION -->
<div class="container">
  <section class="menu">
    <div class="row">
      <div class="col-12">
        <h2 class="section-title">I Nostri Piatti</h2>
        <div class="separator"></div>
      </div>
    </div>

    <app-menu-section [piatti]="piattiAntipasti" sectionTitle="antipasti"></app-menu-section>
    <app-menu-section [piatti]="piattiPrimi" sectionTitle="primi"></app-menu-section>
    <app-menu-section [piatti]="piattiDolci" sectionTitle="dolce"></app-menu-section>
  </section>
</div>
