// the-net-pizza-react/the-net-pizza/src/components/MenuItem.js
import React from "react";
import { Link } from "react-router-dom";


export default function MenuItem({ piatto }) {
  return (
    <div className="col-12 col-sm-6 col-md-4 py-2">
      <div className="card shadow">
        <img
          src={piatto.imageUrl}
          className="card-img-top"
          alt="Tagliere salumi"
        />
        <div className="card-body">
          <h5 className="card-title"><Link to={`/menu/${piatto.id}`}>{piatto.title}</Link> - {piatto.price}€</h5>
          <p className="card-text">
            {piatto.description}
          </p>
        </div>
      </div>
    </div>
  );
}

// the-net-pizza-angular/src/app/menu/menu-item/menu-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Piatto } from 'src/app/@models/menu';

@Component({
  selector: 'app-menu-item',
  templateUrl: './menu-item.component.html',
  styleUrls: ['./menu-item.component.scss']
})
export class MenuItemComponent implements OnInit {

  @Input() piatto: Partial<Piatto> = {};

  constructor() { }

  ngOnInit(): void {
    
  }

}

<div class="card shadow" [class.not-available]="!piatto.available">
  <img
    [src]="piatto.imageUrl"
    class="card-img-top"
    [alt]="piatto.title"
  />
  <div class="card-body">
    <h5 class="card-title">{{ piatto.title | titlecase }} - {{ piatto.price | currency }}</h5>
    <p class="card-text">
      {{ piatto.description }}
    </p>
  </div>
</div>
